# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
      env:
        REACT_APP_SERVER_BASE_URL: "abc" 
        REACT_APP_FB_API_KEY: "abc123abc123abc123abc123abc123abc123abc"                    
        REACT_APP_FB_AUTH_DOMAIN: "abc" 
        REACT_APP_FB_DATABASE_URL: "abc" 
        REACT_APP_FB_PROJECT_ID: "abc" 
        REACT_APP_FB_STORAGE_BUCKET: "abc" 
        REACT_APP_FB_MESSAGING_SENDER_ID: "abc" 
        REACT_APP_FB_APP_ID: "abc" 
        REACT_APP_FB_MEASUREMENT_ID: "abc" 
    - run: yarn
    - run: yarn build
    - run: yarn test